export const themes = {
  default: {
    '--jdv-font-family': "'Courier New', Courier, monospace",
    '--jdv-font-size': '13px',
    '--jdv-color-text':        '#1e1e1e',
    '--jdv-color-text-muted':  '#999',
    '--jdv-color-text-label':  '#555',
    '--jdv-color-string':      '#0a7',
    '--jdv-color-number':      '#07a',
    '--jdv-color-null':        '#999',
    '--jdv-color-date':        '#60a',
    '--jdv-color-error':       '#c00',
    '--jdv-color-accent':      '#0070f3',
    '--jdv-color-bg':          'transparent',
    '--jdv-color-hover':       '#f0f0f0',
    '--jdv-color-border':      '#e0e0e0',
    '--jdv-color-section-border': '#d8d8d8',
    '--jdv-color-bool-on-bg':   '#d4edda',
    '--jdv-color-bool-on-text': '#155724',
    '--jdv-color-bool-off-bg':  '#f8d7da',
    '--jdv-color-bool-off-text':'#721c24',
  },

  dark: {
    '--jdv-font-family': "'Courier New', Courier, monospace",
    '--jdv-font-size': '13px',
    '--jdv-color-text':        '#d4d4d4',
    '--jdv-color-text-muted':  '#666',
    '--jdv-color-text-label':  '#9cdcfe',
    '--jdv-color-string':      '#ce9178',
    '--jdv-color-number':      '#b5cea8',
    '--jdv-color-null':        '#569cd6',
    '--jdv-color-date':        '#c586c0',
    '--jdv-color-error':       '#f48771',
    '--jdv-color-accent':      '#4fc1ff',
    '--jdv-color-bg':          '#1e1e1e',
    '--jdv-color-hover':       '#2a2d2e',
    '--jdv-color-border':      '#3c3c3c',
    '--jdv-color-section-border': '#4a4a4a',
    '--jdv-color-bool-on-bg':   '#1e3a2f',
    '--jdv-color-bool-on-text': '#4ec994',
    '--jdv-color-bool-off-bg':  '#3a1e1e',
    '--jdv-color-bool-off-text':'#e06c75',
  },

  ocean: {
    '--jdv-font-family': "system-ui, sans-serif",
    '--jdv-font-size': '13px',
    '--jdv-color-text':        '#2d3436',
    '--jdv-color-text-muted':  '#74b9ff',
    '--jdv-color-text-label':  '#0984e3',
    '--jdv-color-string':      '#00b894',
    '--jdv-color-number':      '#0984e3',
    '--jdv-color-null':        '#74b9ff',
    '--jdv-color-date':        '#6c5ce7',
    '--jdv-color-error':       '#d63031',
    '--jdv-color-accent':      '#0984e3',
    '--jdv-color-bg':          '#f0f8ff',
    '--jdv-color-hover':       '#dff0ff',
    '--jdv-color-border':      '#b2d8f7',
    '--jdv-color-section-border': '#74b9ff',
    '--jdv-color-bool-on-bg':   '#d0f4ea',
    '--jdv-color-bool-on-text': '#00b894',
    '--jdv-color-bool-off-bg':  '#ffeaa7',
    '--jdv-color-bool-off-text':'#d63031',
  },
};